### ISSUE TITLE
is peerDependencies purposely locked react 16?

### ISSUE THREAD

**Issue by zanona** [lessp/react-is-visible#35]
Hello,
May I please ask if this library isn't compatible with react 17+ as peerDependencies is restricting installations only to react 16?

Thank you.

**Comment by lessp** [comment]
Heya @zanona, thanks for reporting! Should be good to go with 17+. Feel free to try `1.2.0-0` to verify. 🙂

**Comment by zanona** [comment]
Awesome! That was pretty quick! Thanks a lot :+1:

**Comment by lessp** [comment]
Thanks, I'll cut a release!
