### ISSUE TITLE
Version 1.0.2 on NPM doesn't have the newest compiled version of IsVisible

### ISSUE THREAD

**Issue by caleb** [lessp/react-is-visible#8]
I installed 1.0.2 from NPM because I actually want to use a PureComponent version of IsVisible so I can pass props to it and make it re-render when my props change, but the version of `IsVisible.js` in the `lib` directory doesn't look like it uses `PureComponent`.

I compiled my own version of the library and looked at the output and it does work as I expected.

Thanks for this little library, I've looked at lots of options and this is the simplest.

**Comment by lessp** [comment]
Hey @caleb, thanks for your kind words. That's a blunder. I'll take a look and make another release, thanks for letting me know! 🙌

**Comment by lessp** [comment]
Should be fixed in: https://github.com/lessp/react-is-visible/releases/tag/v1.0.3

Thanks for letting me know! 🙏
